name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      CARDBOARD_SECRET: ${{ secrets.CARDBOARD_SECRET }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      CARDBOARD_TOKEN: ${{vars.CARDBOARD_TOKEN}}
      PORT_BINDING: ${{vars.PORT_BINDING}}
      PUBLIC_CARDBOARD_URL: ${{vars.PUBLIC_CARDBOARD_URL}}
      PUBLIC_CURRENT_BOARD: ${{vars.PUBLIC_CURRENT_BOARD}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx zenstack generate && npx prisma generate
      - run: npm run build --if-present